# Generated by Django 2.2 on 2019-04-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('main', '0002_auto_20190420_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
