# Generated by Django 2.2 on 2019-04-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190421_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address1',
            field=models.CharField(default='hjjkh', max_length=200),
            preserve_default=False,
        ),
    ]
