# Generated by Django 2.2 on 2019-05-10 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190510_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='Animal',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 18, 41, 3, 110849)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 18, 41, 3, 109851)),
        ),
    ]
