# Generated by Django 2.2 on 2019-05-10 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190510_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 18, 49, 8, 858001)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='Request',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 18, 49, 8, 858001)),
        ),
    ]
