# Generated by Django 2.2 on 2019-05-10 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190510_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 22, 20, 17, 184325)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 22, 20, 17, 184325)),
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Claimed_date', models.DateTimeField(default=datetime.datetime(2019, 5, 10, 22, 20, 17, 184325))),
                ('Handled', models.DateTimeField(default=datetime.datetime(2019, 5, 10, 22, 20, 17, 184325))),
                ('Insurance_claimed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Insurance')),
            ],
        ),
    ]
