# Generated by Django 2.2 on 2019-05-10 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190510_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='Claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 23, 39, 52, 46771)),
        ),
        migrations.AlterField(
            model_name='claims',
            name='Handled',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 23, 39, 52, 46771)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 23, 39, 52, 46771)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 10, 23, 39, 52, 46771)),
        ),
    ]
