# Generated by Django 2.2 on 2019-05-10 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190510_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='Claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claims',
            name='Claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 0, 17, 0, 447352)),
        ),
        migrations.AlterField(
            model_name='claims',
            name='Handled',
            field=models.DateTimeField(default=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 0, 17, 0, 447352)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 0, 17, 0, 447352)),
        ),
    ]
