# Generated by Django 2.2 on 2019-05-10 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190511_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='Claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 0, 19, 18, 240215)),
        ),
        migrations.AlterField(
            model_name='claims',
            name='Handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 0, 19, 18, 239219)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 0, 19, 18, 239219)),
        ),
    ]
