# Generated by Django 2.2 on 2019-05-10 20:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190511_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='Claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 1, 48, 25, 836742)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 1, 48, 25, 836742)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 1, 48, 25, 836742)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
