# Generated by Django 2.2 on 2019-05-10 20:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190511_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='claims',
            name='Claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 2, 11, 57, 673131)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 2, 11, 57, 673131)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 2, 11, 57, 673131)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
