# Generated by Django 2.2 on 2019-05-10 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190511_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='Claimed_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 2, 45, 3, 238693)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 2, 45, 3, 237696)),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 2, 45, 3, 237696)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
